[project]
name = "data-storage-bet"
version = "0.0.1"
requires-python = ">=3.12"
authors = [
    {name = "Palm"},
    {name = "Arm"},
    {name = "Drake"}
]
dependencies = [
    "psycopg>=3.3.5",
    "python-dotenv>=1.2.3",
    "redis>=5.0.0",
    "sqlalchemy>=2.0.52",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["db", "models", "seed", "redis_client"]

[tool.setuptools.packages.find]
include = ["operations*"]

[dependency-groups]
dev = [
    "psycopg[binary]>=3.3.5",
    "typing>=3.10.0.0",
]
